<html>
<head>
	<title>..::Principal::..</title>
	<?php
		$this->load->view("estructura/head.php");
	?>
</head>
<body>
	<?php
		$this->load->view("estructura/menu.php");
		$this->load->view("ListaClientes/clientes.php");
	?>
</body>
</html>